### ISSUE TITLE
ymusic 不能触发点击，或者不非广告界面触发点击。

### ISSUE THREAD

**Issue by ximalu** [LGH1996/TapClick#22]
看不出规则哪里不对。

![微信图片_20240819153740](https://github.com/user-attachments/assets/2b72dab9-4ad7-473d-8da6-79aa987c2e07)

**Comment by LGH1996** [comment]
看触发次数和时间是已经点击了，没效果要么是找错了控件，要么是该app对无障碍的点击事件做了拦截，大概率是找错了控件，把Id或descibe删了试下。

**Comment by ximalu** [comment]
左上角那个 X 确实是关闭广告的控件。

**Comment by LGH1996** [comment]
两张截图的活动名都不一样，你重新添加下吧

**Comment by ximalu** [comment]
有用! 感谢！  附规则如下。

"RegulationExport": {
  "displayMetrics": {
    "density": 2.75,
    "densityDpi": 440,
    "heightPixels": 2400,
    "noncompatDensityDpi": 440,
    "noncompatHeightPixels": 2400,
    "noncompatWidthPixels": 1080,
    "scaledDensity": 2.75,
    "widthPixels": 1080,
    "xdpi": 398.807,
    "ydpi": 398.806
  },
  "fingerPrint": "Redmi/chopin/chopin:13/TP1A.220624.014/V14.0.8.0.TKPCNXM:user/release-keys",
  "regulationList": [
    {
      "appDescribe": {
        "appName": "YMusic",
        "appPackage": "com.kapp.youtube.final",
        "coordinateOnOff": false,
        "coordinateRetrieveAllTime": true,
        "coordinateRetrieveTime": 20000,
        "id": 409,
        "onOff": true,
        "widgetOnOff": true,
        "widgetRetrieveAllTime": true,
        "widgetRetrieveTime": 20000
      },
      "coordinateList": [],
      "widgetList": [
        {
          "action": 1,
          "appActivity": "com.kapp.youtube.ads.ui.NativeBannerActivity",
          "appPackage": "com.kapp.youtube.final",
          "clickDelay": 0,
          "clickInterval": 500,
          "clickNumber": 1,
          "clickOnly": false,
          "comment": "",
          "condition": 0,
          "createTime": 1724258853531,
          "debounceDelay": 0,
          "id": 11,
          "lastTriggerTime": 1724304458472,
          "noRepeat": false,
          "toast": "",
          "triggerCount": 9,
          "widgetClickable": true,
          "widgetDescribe": "",
          "widgetId": "com.kapp.youtube.final:id/vRemoveAd",
          "widgetRect": {
            "bottom": 2194,
            "left": 413,
            "right": 667,
            "top": 2062
          },
          "widgetText": "关闭广告"
        }
      ]
    }
  ]
}
