### ISSUE TITLE
建议兼容 GKD的规则

### ISSUE THREAD

**Issue by aspfate** [LGH1996/TapClick#5]
跳过软件先要体验好，与时俱进的控件规则不可或缺。目前GKD社区较为繁荣，建议兼容GKD的规则https://github.com/gkd-kit/subscription 这是个独立仓库，最终配置文件为json。

**Comment by LGH1996** [comment]
这是什么有毛病的建议

**Comment by LGH1996** [comment]
这是什么有毛病的建议

**Comment by aspfate** [comment]
别激动，我知道你是这方面的先行者，你的项目AccessibilityTool影响力很多后来的人。respect。如果感受到冒犯了，理解你的心情，并表示歉意。
