### ISSUE TITLE
建议新安装的应用开关是默认关闭的

### ISSUE THREAD

**Issue by twgh** [LGH1996/TapClick#6]
因为没广告的应用是肯定比有广告的应用少的多的

**Comment by PeNgPaiO** [comment]
默认各个应用都不启用，可以尝试制定规则的时候自动启用或者弹框询问后启用

**Comment by twgh** [comment]
因为所有的应用这个开关都默认开着，就导致没有设置规则的应用也会排在前面，想要查看所有已经创建规则的应用需要更进一步的操作，所以需要这个开关默认是关闭的，也更符合直觉。

![Screenshot_20240218134931.jpg](https://github.com/LGH1996/TapClick/assets/54952145/205b9ff7-b65c-40ef-9a88-e0aa54122224)

**Comment by LGH1996** [comment]
已实现
